version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: hashapp_db
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./.env:/.env
      - ./.env:/.env
    ports:
      - "7777:7777"
    environment:
      SERVER_PORT: ":7777"
      JWT_SECRET: "your_jwt_secret_here"
      JWT_TTL_HOURS: "24"
      PG_USER: "postgres"
      PG_PASSWORD: "secretpassword"
      PG_HOST: "db"
      PG_PORT: "5432"
      PG_DB: "hashapp_db"
      PG_SSLMODE: "disable"
    depends_on:
      - db

  # frontend:
  #   build:
  #     context: ../frontend # Путь к папке фронтенда
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - backend
  #   environment:
  #     - VITE_API_URL=http://localhost:7773/api # Переменная окружения для фронтенда

volumes:
  db_data:
